module org.library.btl_oop16_library {
    requires org.xerial.sqlitejdbc;
    requires org.json;
    requires jdk.compiler;
    requires com.google.zxing;
    requires com.google.zxing.javase;
    requires org.apache.poi.ooxml;
    requires atlantafx.base;
    requires jakarta.mail;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.ikonli.material2;
    requires MaterialFX;
    requires AnimateFX;
    requires java.net.http;
    requires langchain4j.github.models;
    requires jcommander;
    requires annotations;
    requires javafx.graphics;
    requires eu.iamgio.animated;
    requires io.github.cdimascio.dotenv.java;

    opens org.library.btl_oop16_library to javafx.fxml;
    exports org.library.btl_oop16_library;
    exports org.library.btl_oop16_library.model;
    opens org.library.btl_oop16_library.model to javafx.fxml;
    exports org.library.btl_oop16_library.utils.database;
    opens org.library.btl_oop16_library.utils.database to javafx.fxml;
    exports org.library.btl_oop16_library.utils.general;
    opens org.library.btl_oop16_library.utils.general to javafx.fxml;
    exports org.library.btl_oop16_library.services;
    opens org.library.btl_oop16_library.services to javafx.fxml;
    exports org.library.btl_oop16_library.controller.authentication;
    opens org.library.btl_oop16_library.controller.authentication to javafx.fxml;
    exports org.library.btl_oop16_library.controller.views;
    opens org.library.btl_oop16_library.controller.views to javafx.fxml;
    exports org.library.btl_oop16_library.controller.dialogs;
    opens org.library.btl_oop16_library.controller.dialogs to javafx.fxml;
    exports org.library.btl_oop16_library.controller.general;
    opens org.library.btl_oop16_library.controller.general to javafx.fxml;
    exports org.library.btl_oop16_library.controller.items;
    opens org.library.btl_oop16_library.controller.items to javafx.fxml;
    exports org.library.btl_oop16_library.controller.views.settings;
    opens org.library.btl_oop16_library.controller.views.settings to javafx.fxml;
}